-- MySQL Script generated by MySQL Workbench
-- Model: network    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema network
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema network
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `network` DEFAULT CHARACTER SET utf8 ;
USE `network` ;

-- -----------------------------------------------------
-- Table `network`.`countries`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `network`.`countries` (
  `id_country` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ISO` VARCHAR(2) NOT NULL,
  `COUNTRY` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_country`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `network`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `network`.`users` (
  `id_user` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `guid` VARCHAR(20) NOT NULL,
  `username` VARCHAR(20) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `created_at` DATE NOT NULL,
  `id_country` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `id_user_UNIQUE` (`id_user` ASC),
  UNIQUE INDEX `user_UNIQUE` (`username` ASC),
  UNIQUE INDEX `guid_UNIQUE` (`guid` ASC),
  INDEX `fk_users_countries1_idx` (`id_country` ASC),
  CONSTRAINT `fk_users_countries1`
    FOREIGN KEY (`id_country`)
    REFERENCES `network`.`countries` (`id_country`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `network`.`quotes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `network`.`quotes` (
  `id_quote` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `quote` VARCHAR(120) NOT NULL,
  `post_date` DATE NOT NULL,
  `post_time` TIME NOT NULL,
  `likes` INT UNSIGNED NOT NULL DEFAULT 0,
  `id_user` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_quote`),
  UNIQUE INDEX `id_quote_UNIQUE` (`id_quote` ASC),
  INDEX `fk_quotes_users_idx` (`id_user` ASC),
  CONSTRAINT `fk_quotes_users`
    FOREIGN KEY (`id_user`)
    REFERENCES `network`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `network`.`likes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `network`.`likes` (
  `id_user` INT UNSIGNED NOT NULL,
  `id_quote` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id_user`, `id_quote`),
  INDEX `fk_likes_quotes1_idx` (`id_quote` ASC),
  CONSTRAINT `fk_likes_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `network`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_likes_quotes1`
    FOREIGN KEY (`id_quote`)
    REFERENCES `network`.`quotes` (`id_quote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
